source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MCStackView_Example', :exclusive => true do
  pod "MCStackView", :path => "../"
end

target 'MCStackView_Tests', :exclusive => true do
  pod "MCStackView", :path => "../"

  pod 'Quick', git: 'https://github.com/Quick/Quick', branch: 'swift-2.0'
  pod 'Nimble', git: 'https://github.com/Quick/Nimble', branch: 'swift-2.0'
end
